DELIMITER $$

CREATE FUNCTION CONV_DRNK(input1 text) RETURNS int
    DETERMINISTIC
BEGIN
	IF input1=1 THEN
		RETURN 1;
	ELSEIF input1 <=2 THEN
		RETURN 2;
    ELSEIF input1 <=3 THEN
		RETURN 3;
	ELSEIF input1 <=5 THEN
		RETURN 4;
	ELSE
		RETURN 5;
	END IF;
END