DELIMITER $$

CREATE FUNCTION CONV_DRKQTY(input1 text) RETURNS int
    DETERMINISTIC
BEGIN
	IF input1=0 THEN
		RETURN 0;
	ELSEIF input1 <4 THEN
		RETURN 1;
    ELSEIF input1 <=7 THEN
		RETURN 2;
	ELSEIF input1 <11 THEN
		RETURN 3;
	ELSE
		RETURN 4;
	END IF;
END