UPDATE `pred`.`gj_an100_CON`
SET
`HCHK_APOP_PMH_YN` = IS_APOP(HCHK_CONCATED),
`HCHK_DIABML_PMH_YN` = IS_DIABML(HCHK_CONCATED),
`HCHK_ETCDSE_PMH_YN` = IS_ETCDSE(HCHK_CONCATED),
`HCHK_HDISE_PMH_YN` = IS_HDISE(HCHK_CONCATED),
`HCHK_HPLPDM_PMH_YN` =0,
`HCHK_HPRTS_PMH_YN` = IS_HPRTS(HCHK_CONCATED),
`HCHK_PHSS_PMH_YN` = IS_PHSS(HCHK_CONCATED)