UPDATE `pred`.`gj_2008`
SET
`PAST_SMK_TERM_RSPS_CD` = CONV_SMK(SMK_TERM_RSPS_CD),
`CUR_SMK_TERM_RSPS_CD` = CONV_SMK(SMK_TERM_RSPS_CD),
`PAST_DSQTY_RSPS_CD` = CONV_DSQTY(DSQTY_RSPS_CD),
`CUR_DSQTY_RSPS_CD` = CONV_DSQTY(DSQTY_RSPS_CD),
`DRNK_HABIT_RSPS_CD` = CONV_DRNK(DRNK_HABIT_RSPS_CD),
`TM1_DRKQTY_RSPS_CD` = CONV_DRKQTY(TM1_DRKQTY_RSPS_CD),
`MOV20_WEK_FREQ_ID` = CONV_EXERCI(EXERCI_FREQ_RSPS_CD),
`MOV30_WEK_FREQ_ID` = CONV_EXERCI(EXERCI_FREQ_RSPS_CD),
`WLK30_WEK_FREQ_ID` = CONV_EXERCI(EXERCI_FREQ_RSPS_CD)