#혈청지오티
DELIMITER $$

CREATE FUNCTION CLASS_AST(input1 text) RETURNS int
	DETERMINISTIC
BEGIN
	IF input1<=40 THEN
    	RETURN 0;
	ELSEIF input1<51 THEN
    	RETURN 1;
	ELSE
    	RETURN 2;
	END IF;
END;