CREATE TABLE JK_UNIF_1 AS
(
SELECT *
FROM JK_COPY
)
;
UPDATE JK_UNIF_1
SET
AGE_GROUP=CLASS_AGE(AGE_GROUP)
WHERE AGE_GROUP IS NOT NULL AND NOT AGE_GROUP=""
;
UPDATE JK_UNIF_1
SET
SIDO=CLASS_SIDO(SIDO)
WHERE SIDO IS NOT NULL AND NOT SIDO=""
;
UPDATE JK_UNIF_1
SET
IPSN_TYPE_CD=CLASS_IPSN(IPSN_TYPE_CD)
WHERE IPSN_TYPE_CD IS NOT NULL AND NOT IPSN_TYPE_CD=""
;
UPDATE JK_UNIF_1
SET
CTRB_PT_TYPE_CD=CLASS_CTRB(CTRB_PT_TYPE_CD)
WHERE CTRB_PT_TYPE_CD IS NOT NULL AND NOT CTRB_PT_TYPE_CD=""
;
CREATE TABLE JK_UNIF AS
(
SELECT *
FROM JK_UNIF_1
)
;
CREATE INDEX person ON JK_UNIF(PERSON_ID,STND_Y)
